# This file contains the configuration settings for your Cedar app.
# This file is also what makes your Cedar app a Cedar app.
# If you remove it and try to run `yarn cedar dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://cedarjs.com/docs/app-configuration-redwood-toml

[web]
  title = "Cedar App"
  port = 8910
  apiUrl = "/.redwood/functions"
  includeEnvironmentVariables = [
    # Add any ENV vars that should be available to the web side to this array
    # See https://cedarjs.com/docs/environment-variables#web
  ]
[api]
  port = 8911
[browser]
  open = true
[notifications]
  versionUpdates = ["latest"]
